name: "Auto audit"
author: "ixuz"
inputs:
  args:
    required: false
    default: ""
  token:
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ inputs.token }}
    - name: Audit dependencies
      run: npm audit
      shell: bash
