name: "Auto audit"
author: "ixuz"
inputs:
  token:
    required: false
    default: ${{ github.token }}
  fetch-depth:
    required: false
    default: 0
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}
        fetch-depth: ${{ inputs.fetch-depth }}
    - name: Audit dependencies
      run: npm audit fix --force
      shell: bash
    - uses: iotakingdoms/actions/packages/cached-npm-ci@main
      with:
        args: "--ignore-scripts"
    - name: Build
      run: npm run build
      shell: bash
    - name: Build
      run: npm run test
      shell: bash
