name: Release Docker
author: "ixuz"
inputs:
  registry-url:
    required: true
  token:
    required: true
  fetch-depth:
    required: false
    default: 0
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
    - name: Log in to the Container registry
      uses: docker/login-action@6af3c118c8376c675363897acf1757f7a9be6583
      with:
        registry: ${{ inputs.registry-url }}
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@47c365107cb34e788d99cf3d89acf424b505b3e8
      with:
        images: ${{ inputs.registry-url }}/${{ github.repository }}
        tags: |
          type=ref,event=tag
          type=semver,pattern={{version}}
    - name: Build and push Docker image
      uses: docker/build-push-action@fe02965b4878556fce19e4f0aa608d7d09ed629b
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
