name: Release Docker
author: "ixuz"
inputs:
  registry-url:
    required: true
  token:
    required: true
  fetch-depth:
    required: false
    default: 0
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
    - name: Log in to the Container registry
      uses: docker/login-action@f6d32ad0236599ffe0bb261e71184c3e4e1d47cd
      with:
        registry: ${{ inputs.registry-url }}
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@70b2cdc6480c1a8b86edf1777157f8f437de2166
      with:
        images: ${{ inputs.registry-url }}/${{ github.repository }}
        tags: |
          type=ref,event=tag
          type=semver,pattern={{version}}
    - name: Build and push Docker image
      uses: docker/build-push-action@f7a2a67b4c1059633be6daa491784d8ac6a7ed6d
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
