name: "Cached npm ci"
author: "ixuz"
inputs:
  token:
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ inputs.token }}
    - uses: actions/setup-node@v2
      with:
        node-version: 17.x
    - uses: actions/cache@v2
      id: cached-dependencies
      env:
        cache-name: node-modules
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-cache-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cached-dependencies.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
