name: "Cached npm ci"
author: "ixuz"
inputs:
  args:
    required: false
    default: ""
  token:
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ inputs.token }}
    - uses: actions/setup-node@v2
      with:
        node-version: 17.x
    - uses: actions/cache@v2
      id: cached-dependencies
      env:
        cache-name: cached-npm-ci
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ env.cache-name }} ${{ inputs.args }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm ci ${{ inputs.args }}
