name: Release version
author: "ixuz"
inputs:
  github_token:
    required: true
    default: ${{ github.token }}
  npm_token:
    required: true
  fetch-depth:
    required: false
    default: 0
runs:
  using: "composite"
  steps:
    - uses: iotakingdoms/actions/packages/release-npm@main
      with:
        repository-url: https://npm.pkg.github.com
        token: ${{ inputs.github_token }}
    - uses: iotakingdoms/actions/packages/release-npm@main
      with:
        repository-url: https://registry.npmjs.org
        token: ${{ inputs.npm_token }}
