name: Release version
author: "ixuz"
inputs:
  github-token:
    required: true
  npm-token:
    required: true
  fetch-depth:
    required: false
    default: 0
runs:
  using: "composite"
  steps:
    - uses: iotakingdoms/actions/packages/release-npm@main
      with:
        repository-url: https://registry.npmjs.org
        token: ${{ inputs.npm-token }}
    - uses: iotakingdoms/actions/packages/release-npm@main
      with:
        repository-url: https://npm.pkg.github.com
        token: ${{ inputs.github-token }}
