name: Release NPM
author: "ixuz"
inputs:
  repository-url:
    required: true
  token:
    required: true
  fetch-depth:
    required: false
    default: 0
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Node
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
      uses: actions/setup-node@v3
      with:
        node-version: "17.x"
        registry-url: ${{ inputs.repository-url }}
        fetch-depth: ${{ inputs.fetch-depth }}
    - name: Publish to NPM registry
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
      run: |
        npm ci
        npm run lint
        npm run build
        npm run test
        npm publish --access public
      shell: bash
